artifact_uri: /home/animesh45/TAMLEP/mle-training/minus/472890792625089328/edcce426913a4d6baf1dbbbcbe0519a2/artifacts
end_time: 1710443262374
entry_point_name: ''
experiment_id: '472890792625089328'
lifecycle_stage: active
run_id: edcce426913a4d6baf1dbbbcbe0519a2
run_name: Main_function
run_uuid: edcce426913a4d6baf1dbbbcbe0519a2
source_name: ''
source_type: 4
source_version: ''
start_time: 1710443152603
status: 3
tags: []
user_id: animesh45
